import { launchChromium } from './lib/browser.mjs';
const SP = '/tmp/claude-0/-home-user-TruegleSearch/f9c878a7-ce12-5f85-a4ca-a7f4610f37c7/scratchpad';
const b = await launchChromium();
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
await ctx.addInitScript("localStorage.setItem('truegle_install_dismissed_at', String(Date.now()))");
const p = await ctx.newPage();
const errs = []; const bad = [];
p.on('pageerror', (e) => errs.push(e.message.slice(0, 120)));
p.on('response', (r) => { if (r.status() >= 400 && /truegle|vercel/.test(r.url())) bad.push(`${r.status()} ${r.url().slice(0, 90)}`); });
await p.goto('https://truegle.info/', { waitUntil: 'domcontentloaded', timeout: 60000 });
await p.waitForSelector('[data-tile]', { timeout: 30000 });
await p.waitForTimeout(2500);
const tiles = await p.evaluate(`[...document.querySelectorAll('[data-tile]')].map((e) => e.dataset.tile + ':' + e.dataset.open + '@' + Math.round(e.getBoundingClientRect().x))`);
console.log('tiles:', tiles.join(' '));
await p.evaluate(`document.querySelector('[data-landing-modules]').scrollIntoView({block:'start'})`);
await p.waitForTimeout(800);
await p.screenshot({ path: `${SP}/prod-1-tiles.png` });
console.log('why after scroll:', await p.locator('[data-tile="why"]').getAttribute('data-open'));
await p.locator('[data-tile="news"]').dispatchEvent('click');
await p.waitForSelector('[data-news-video]', { timeout: 40000 }).catch(() => console.log('NO NEWS VIDEOS RENDERED'));
console.log('news videos:', await p.locator('[data-news-video]').count(), '| first:', (await p.locator('[data-news-video]').first().innerText().catch(() => '')).replace(/\n/g, ' | ').slice(0, 90));
await p.screenshot({ path: `${SP}/prod-2-news.png` });
await p.locator('[data-tile="markets"]').dispatchEvent('click');
await p.waitForTimeout(3500);
console.log('markets rows:', await p.locator('[data-news-body="markets"] .tabular-nums').count(), '| analysis videos:', await p.locator('[data-news-body="markets"] [data-news-video]').count());
await p.screenshot({ path: `${SP}/prod-3-markets.png` });
await p.locator('[data-tile="news"]').dispatchEvent('click');
await p.waitForSelector('[data-news-video]', { timeout: 20000 });
await p.locator('[data-news-video]').first().click();
await p.waitForURL(/\/feed/, { timeout: 20000 }).catch(() => {});
console.log('after tap url:', p.url().replace('https://truegle.info', '').slice(0, 110));
await p.waitForTimeout(6000);
console.log('player iframe:', await p.locator('[data-mini] iframe').count(), (await p.locator('[data-mini] iframe').first().getAttribute('src').catch(() => '') || '').slice(0, 70));
await p.screenshot({ path: `${SP}/prod-4-feed.png` });
console.log('page errors:', errs.slice(0, 4), '| 4xx/5xx on our hosts:', bad.slice(0, 5));
await b.close();
